### ISSUE TITLE
Preserve space between selector and > combinator

### ISSUE THREAD

**Issue by smonff** [beautify-web/js-beautify#1044]
When beautifying a CSS rule containing a [`>` combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors), the combinator got stuck to the previous selector. Actually, even if it already formatted correctly, the space is removed. It makes quite difficult to use `js-beautify` in CSS files containing > combinators because it will produce selectors that won't work. 

# Input
The code looked like this before beautification:
```
.foo > h3 {
    ...
}
```

# Expected Output
I would expect the input to not change. The code should have looked like this after beautification:
```
/* Space here
    V */
.foo > h3 {
    ...
}
```

# Actual Output
The  code actually looked like this after beautification:
```
/* No space 
   V */
.foo> h3 {
    ...
}
```

## Environment
OS: Archlinux with Emacs [web-beautify.el](https://github.com/yasuyk/web-beautify)

Also tested under command line only outside of Emacs.

## Settings
Defaults

**Comment by smonff** [comment]
It has been fixed in `1.6.4`, it don't happen anymore since I set `space_around_combinator` to true, my bad. This param should be true by default though.

**Comment by subfighter3** [comment]
Hello! I still have a "no space" around any sibiling selector when I beautify a css file.
I actually use atom-beautify.

**Comment by NSExceptional** [comment]
Me too

**Comment by bitwiseman** [comment]
@NSExceptional @subfighter3 

https://beautifier.io/ with setting:

```json
{
"space_around_combinator": true
}
```

Formats as expected.  Fix will be needed in atom beautifier.

**Comment by NSExceptional** [comment]
Thanks!

**Comment by subfighter3** [comment]
Thank you!
