### ISSUE TITLE
es6 destructuring

### ISSUE THREAD

**Issue by iksose** [beautify-web/js-beautify#511]
```javascript
function takeThing({prop}) {
    console.log("inner prop", prop)
}
```
is being reformatted to
```javascript
function takeThing({
    prop
}) {
    console.log("inner prop", prop)
}
```

I don't think this is intentional.

**Comment by mvpspl619** [comment]
Will there be support for the new ECMAScript syntax ?

**Comment by bitwiseman** [comment]
Eventually.   It will probably happen as people point out specific cases that need doing.

**Comment by amacdougall** [comment]
I'm trying to come up with a good way of doing this right now, but it's going to be a bit of a challenge. Part of the trouble is that destructuring identifiers can occur in various surrounding contexts:

```
var <destructuring> = input; // or let or const

var <destructuring> = input, <destructuring> = input_2; // possibly on separate lines

var a = 1,
    <destructuring> = input;

function(<destructuring>) {
  // implementation
};

<destructuring> => returnValue; // an arrow function

(<destructuring>, <destructuring>) => returnValue; // multi-param arrow function
```

I might even be missing a few right now. And then the destructuring form itself can be nested:

```javascript
let functions = [
  [a, {b, [c, {d, e}, f]}] => [a, b, c, d, e, f] // this is totally valid, people
  {a, [{b}, {c}, {d}, {e, f}]} => [a, b, c, d, e, f] // so is this, and so on
];
```

It's a small blessing that you can't nest objects directly in a destructuring form.

**Comment by bitwiseman** [comment]
Fixed.

**Comment by JoyceBabu** [comment]
@bitwiseman I still seeing this issue? Is there an option for enabling the fix?

**Comment by bitwiseman** [comment]
@JoyceBabu Please file an issue with the details.

**Comment by JoyceBabu** [comment]
@bitwiseman  I found out the option name from another issue. Fixed by setting `"brace_style": "collapse-preserve-inline"`. Thank you.

**Comment by bitwiseman** [comment]
@JoyceBabu 
Glad you found it.  😄  Please use `"collapse,preserve-inline"`.
